name: Build and Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64, aarch64]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build (Release)
        run: cargo build --release --target ${{ matrix.target }}-unknown-linux-gnu

      - name: Package artifact
        run: |
          cd target/${{ matrix.target }}-unknown-linux-gnu/release
          zip rnmedia-${{ matrix.target }}.zip rnmedia

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}-unknown-linux-gnu/release/rnmedia-${{ matrix.target }}.zip
